### ISSUE TITLE
crash after clicking Run iS-CellR

### ISSUE THREAD

**Issue by JessicaOsterhout** [immcore/iS-CellR#1]
I loaded the Malignant50.csv file and after selecting the "Quality control and cell filtering" step and clicking Run iS-CellR, I get the following output on R and then it crashes. This is before selecting any quality control/filtering parameters. 

Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene means
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variance to mean ratios
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Warning in normalizePath(path = fast_tsne_path) :
  path[1]="/bin/fast_tsne": No such file or directory
Warning: Error in fftRtsne: fast_tsne_path '/bin/fast_tsne' does not exist or is not executable
  81: stop
  80: fftRtsne
  79: RunTSNE
  74: observeEventHandler [/private/var/folders/fv/6p2sdnqx7wl4d2qt_vms4nfm0000gn/T/RtmplS3qff/shinyapp10ffb272e2987/iS-CellR-master/server.R#813]
   3: runApp
   2: runUrl
   1: shiny::runGitHub

**Comment by mitul-patel** [comment]
Hi Jessica,

Many thanks for trying the tool. Have you installed UMAP and FItSNE before running the app. If not here are the links to install them. UMAP: https://github.com/lmcinnes/umap and FItSNE: https://github.com/KlugerLab/FIt-SNE.

Then you need to specify path for FItSNE (full installation path).
Edit scripts/SeuratRUN.R - Change /bin/fast_tsne to your path
FROM : scObject$val <- RunTSNE(object = scObject$val, reduction.use = "pca", dims.use = 1:75, tsne.method = "FIt-SNE", nthreads = 4, reduction.name = "FItSNE", reduction.key = "FItSNE_", fast_tsne_path = "/bin/fast_tsne", max_iter = 2000)

TO: scObject$val <- RunTSNE(object = scObject$val, reduction.use = "pca", dims.use = 1:75, tsne.method = "FIt-SNE", nthreads = 4, reduction.name = "FItSNE", reduction.key = "FItSNE_", fast_tsne_path = "/bin/fast_tsne", max_iter = 2000)
 
Similarly edit scripts/QCrun.R
 FROM : scObject$val <- RunTSNE(object = scObject$val, reduction.use = "pca", dims.use = 1:75, tsne.method = "FIt-SNE", nthreads = 4, reduction.name = "FItSNE", reduction.key = "FItSNE_", fast_tsne_path = "/bin/fast_tsne", max_iter = 2000)

TO: scObject$val <- RunTSNE(object = scObject$val, reduction.use = "pca", dims.use = 1:75, tsne.method = "FIt-SNE", nthreads = 4, reduction.name = "FItSNE", reduction.key = "FItSNE_", fast_tsne_path = "/bin/fast_tsne", max_iter = 2000)

I hope it helps. Let me know if you still find any problem.
 
Regards,
Mitul
